on:
  pull_request:
  push:
  workflow_dispatch:
  
jobs:
  build-windows:
    strategy:
      matrix:
        debug_x86:
          mode: debug
          arch: x86
          platform: windows
        debug_x64:
          mode: debug
          arch: x64
          platform: windows
        debug_arm:
          mode: debug
          arch: arm
          platform: windows
        debug_arm64:
          mode: debug
          arch: arm64
          platform: windows
        debug_arm64ec:
          mode: debug
          arch: arm64ec
          platform: windows
        release_x86:
          mode: release
          arch: x86
          platform: windows
        release_x64:
          mode: release
          arch: x64
          platform: windows
        release_arm:
          mode: release
          arch: arm
          platform: windows
        release_arm64:
          mode: release
          arch: arm64
          platform: windows
        release_arm64ec:
          mode: release
          arch: arm64ec
          platform: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a ${{ matrix.arch }} -m ${{ matrix.mode }} -p ${{ matrix.platform }} -v -y

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.mode }}-${{ matrix.platform }}-${{ matrix.arch }}-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.arch }}/${{ matrix.mode }}/
